import './globals.css'
import type { Metadata } from 'next'
import { Varela_Round } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react'

const varela_round = Varela_Round({ weight: '400', subsets: ['latin'], variable: '--font-varela-round' })

export const metadata: Metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${varela_round.variable}`}>
      <head>
        <link rel="icon" href="/favicon/favicon.svg" sizes='any' />
      </head>
      <body>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
